### PR TITLE
Non regression test

### PR DESCRIPTION
**Pull request by guillaumecherel**
## Reference to a related issue
Targetting #64

### Changes to pre-existing code

Options that were related to parameter tuning (grid search or optimization method as well) in `.env` or in `src/evaluation/config/retriever_reader_eval_squad_config.py` (experiment name) were moved to a separate dictionary in the latter config file.

Elasticsearch hostname and port was made configurable through environment variables.

Grid search and bayesian optimization tuning method were given there own functions in `src/evaluation/retriever_reader/retriever_reader_eval_squad.py` for clarity.

Moved the main body of the pipeline in `src/evaluation/retriever_reader/retriever_reader_eval_squad.py` to its own function `tune_pipeline` to easily call it from other python files. The main body now calls it.

### Addition of a job to run non-regression tests

The necessary files to run the job were added to `non-regression-tests/`.

The crontab triggers the tests at 4 am everyday.

The script `non-regression-tests/non-regression-tests` is the entrypoint. it pulls the last changes from the github repo and triggers the actual tests (in `non-regression-tests/non-regression-tests.py`) unless there were no new commits since the last tests were run.

The Dockerfile and docker-compose.yml take care of packaging the environment to run the tests.

The file `non-regression-tests/README.md` describes the deployment process: copy the folder to the host that will run the tests,
create the files `non-regression-tests/.env` and `non-regression-tests/known_hosts` and run `docker-compose up -d` to deploy. 

## (Optionnal) Description or justification of specific technical choices that were made

Moving the parameter tuning options to config file was done to facilitate changing those options from a script, as in `non-regression-tests/non-regression-tests.py`.

### CODE REVIEW

**Comment by guillaumecherel** [comment]
Missing yet from our discussions:
- sending mails when the performance drops
- testing that the gpu is free before running the tests.

I can take care of sending mails nextweek. GPU monitoring seems to be complicated: all the gpu monitoring tools I've tried on gpubro are crashing I would have to investigate if it's important.

**Comment by guillaumecherel** [comment]
I'm realizing that the tests should probably only log the best run from the gridsearch, the one that would actually be used in deployment, rather than all of them. Which metrics do you use to chose the best?

**Comment by psorianom** [comment]
Hi @guillaumecherel !
I see you are doing two big changes in this PR: 
1. Changes to pre-existing code
2. Addition of a job to run non-regression tests

Would it be possible to split them in two separate PRs?  That would make it way easier to check if everything is still working.

**Comment by guillaumecherel** [comment]
Yes, I'm closing this PR and will open two new ones.

**Pull request closed without merging**
