### PR TITLE
Guillim cnil update

### PR DESCRIPTION
**Pull request by guillim**
## Why is the change needed
Updating the database for CNIL

## Description of the change
They added the links, so buttons can appear !

## @mentions of the persons responsible for reviewing 
@Rob192 

Once approved, I will update the production database using our new deployment pipelines with ansible !

### CODE REVIEW

**Review by Rob192 — CHANGES_REQUESTED** [review]
this need update from CNIL

**Comment by guillim** [comment]
Updated with the new one from the CNIL. Just waiting for your approval @Rob192

**Review by Rob192 — CHANGES_REQUESTED** [review]
Hello @guillim !
There are several things to change
- The "version" field of the squad.json should be updated to 'besoindaide_PIAF_V6" as required per our versioning system. 
- We should clean up and move all raw data to "raw_and_preparation" ? 
- In addition, when pushing new squad.json, we should make sure it works with our evaluation scripts. By "it works" I mean that we are not getting "conversion errors from Haystack : `There were conversion errors for question ids: ['missing', ...']`

I think we should outline the procedure a bit better so everyone can push squad files. I can take care for this PR if you prefer, as the documentation is not available yet :/

**Comment by guillim** [comment]
yep go for it !

**Comment by guillim** [comment]
A new PR was open, this one is deprecated

**Pull request closed without merging**
