### PR TITLE
Refactor pipeline construction.

### PR DESCRIPTION
**Pull request by guillaumecherel**
## Reference to a related issue

This changes precedes using YAML for pipeline creation, #39.

## Why is the change needed

Pipeline construction in piaf-ml is scattered accross different scripts, which creates a risk of discrepancy between different evaluation scripts. For example, the retrievers used in the retriever only and the retriever + reader evaluation scripts are not always consistent. This refactoring puts pipeline creation in a single module which serves as a central reference for pipeline definition.

## Description of the change

This is a lot of moving code around, here is a little summary of the refactoring to help you follow along:

- Move pipeline construction originally in `src/evaluation/retriever/retriever_eval_squad.py` and `src/evaluation/retriever_reader/retriever_reader_eval_squad.py` to the new module src.evaluation.utils.pipelines
- This root module contains functions that build pipelines given a parameter dictionnary and a few other arguments. They are responsible for calling the right pipeline constructor function from the values in the parameter dict.
- There are two submodules: `custom_pipelines` and `components`.
- The `custom_pipelines` submodule contains functions that build pipelines.
- The `components` submodule contains functions that create the custom components used in the pipelines defined in the `custom_pipelines` submodule.

## (Optionnal) Description or justification of specific technical choices that were made

Comment on using bare haystack Pipeline objects:  I eliminated the use of custom pipeline classes and use bare "haystack" Pipeline objects instead. The reason for this is that production does not use these custom classes and we want piaf-ml to be closer to production to reduce the risk of discrepancy between piaf-ml and prod. Also, the custom pipelines didn't do much beside building the bare Pipeline instance. (Some custom classes remain but those aren't used in the retriever and retriever+reader evaluation scripts.)

### CODE REVIEW

**Comment by guillaumecherel** [comment]
This is a draft PR for the moment for the 2 following reason:

1. The class TitleEmbeddingRetriever in `deployment/roles/haystack/files/custom_components.py` does not work when I try to use it to build the pipeline. (discussed with @guillim) I'm getting the following error:

```python
~/Work/Dev/2021/piaf-ml/deployment/roles/haystack/files/custom_component.py in embed_passages(self, docs)
     63         documents = self.embedding_encoder.embed(texts)
     64         for doc in documents:
---> 65             doc = doc.to_dict()
     66             doc["meta"]["weight"] = self.weight_when_document_found
     67             doc = Document.from_dict(doc, field_map={})

AttributeError: 'numpy.ndarray' object has no attribute 'to_dict'
```


For the moment, the pipelines are built using the TitleEmbeddingRetriever from `src/evaluation/utils/TitleEmbeddingRetriever.py`, but this one does not work either (and we should use the former to use the one used in production)

2. I didn't test the google retriever yet. It sleeps for something like 2 minutes between each query. Is there a way to speed it up for testing?

**Comment by guillaumecherel** [comment]
Rebasing to incorporate the changes from #152 and #114 fixed the issue about the TitleEmbeddingRetriever.

**Review by Rob192 — APPROVED** [review]

**Comment by psorianom** [comment]
Hi @guillaumecherel !
With your refactoring, has it changed the way we start the experiments (with a config file and with a `evaluation_retriever_reader.py` script (or similar)) ? If so, could you add the differences to the description of this PR? If not, I think it LGTM.

**Comment by guillaumecherel** [comment]
Hi @psorianom, We still use the same config files and evaluation scripts as before.
I tested the refactoring with the two scripts
- `src/evaluation/retriever/retriever_eval_squad.py`
- `src/evaluation/retriever_reader/retriever_reader_eval_squad.py`

**Pull request merged**
