### PR TITLE
Update pipeline dila

### PR DESCRIPTION
**Pull request by guillim**
## Why is the change needed
To allow the auto-complete in the DILA pipeline

## Description of the change
Simple copy paste from the CNIL pipeline

### CODE REVIEW

**Review by guillim — COMMENTED** [review]
Should we add the LabelEsRetriever to this PR @Rob192  ?

**Comment by Rob192** [comment]
> Should we modify the dila_2 at the same time, to add the LabelEsRetriever @Rob192 ?

Yes I think !

**Comment by guillim** [comment]
What do you think of this pipeline @Rob192  (you can test it [here](search.piaf.etalab.studio/dila_2))

**Comment by Rob192** [comment]
I cannot see any question completion on the link you sent ?

**Comment by guillim** [comment]
the Autocomplete feature exist in this pipeline. What you are refering to is the frontend feature, therefore it's in the repo piaf_agent. I just changed it so you can see this live now as well !

**Comment by guillim** [comment]
I am now thinking : do we still need dila ? Could be simply replace dila by dila_2 ? @Rob192

**Comment by Rob192** [comment]
Yes, on my side I think our best shot is dila_2, it contains all our latest changes.

**Comment by guillim** [comment]
Well this PR should be ready for your review @Rob192 !

**Review by Rob192 — APPROVED** [review]

**Pull request merged**
